09:02:28 PM:DEBUG [logger_base.py:12] Mensaje Debug
10:48:12 PM:DEBUG [conexion.py:24] Conexión Exitosa: <connection object at 0x0000025AB86AB890; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
10:49:15 PM:DEBUG [conexion.py:24] Conexión Exitosa: <connection object at 0x000001E997A5B890; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
10:49:15 PM:DEBUG [conexion.py:37] Se abrio correctamente el cursor: <cursor object at 0x000001E996117BC0; closed: 0>
